export const THEMES = [
  // --- LIGHT SOFT THEMES (16) ---
  {
    name: "light",
    label: "Cloud (Light)",
    type: "light",
    colors: {
      bg: "#f8fafc",
      surface: "#ffffff",
      primary: "#3b82f6",
      secondary: "#64748b",
      accent: "#60a5fa",
      textPrimary: "#0f172a",
      textSecondary: "#475569",
      border: "#e2e8f0",
    },
  },
  {
    name: "sakura",
    label: "Sakura",
    type: "light",
    colors: {
      bg: "#fff5f7",
      surface: "#ffffff",
      primary: "#f472b6",
      secondary: "#fb7185",
      accent: "#fda4af",
      textPrimary: "#831843",
      textSecondary: "#be185d",
      border: "#fce7f3",
    },
  },
  {
    name: "matcha",
    label: "Matcha",
    type: "light",
    colors: {
      bg: "#f0fdf4",
      surface: "#ffffff",
      primary: "#22c55e",
      secondary: "#16a34a",
      accent: "#86efac",
      textPrimary: "#14532d",
      textSecondary: "#166534",
      border: "#dcfce7",
    },
  },
  {
    name: "sand",
    label: "Sand",
    type: "light",
    colors: {
      bg: "#fefce8",
      surface: "#ffffff",
      primary: "#eab308",
      secondary: "#ca8a04",
      accent: "#fde047",
      textPrimary: "#713f12",
      textSecondary: "#854d0e",
      border: "#fef9c3",
    },
  },
  {
    name: "lilac",
    label: "Lilac",
    type: "light",
    colors: {
      bg: "#faf5ff",
      surface: "#ffffff",
      primary: "#a855f7",
      secondary: "#9333ea",
      accent: "#d8b4fe",
      textPrimary: "#581c87",
      textSecondary: "#6b21a8",
      border: "#f3e8ff",
    },
  },
  {
    name: "apricot",
    label: "Apricot",
    type: "light",
    colors: {
      bg: "#fff7ed",
      surface: "#ffffff",
      primary: "#fb923c",
      secondary: "#f97316",
      accent: "#ffedd5",
      textPrimary: "#7c2d12",
      textSecondary: "#9a3412",
      border: "#ffedd5",
    },
  },
  {
    name: "sky",
    label: "Sky",
    type: "light",
    colors: {
      bg: "#f0f9ff",
      surface: "#ffffff",
      primary: "#0ea5e9",
      secondary: "#0284c7",
      accent: "#7dd3fc",
      textPrimary: "#0c4a6e",
      textSecondary: "#075985",
      border: "#e0f2fe",
    },
  },
  {
    name: "pear",
    label: "Pear",
    type: "light",
    colors: {
      bg: "#f7fee7",
      surface: "#ffffff",
      primary: "#84cc16",
      secondary: "#65a30d",
      accent: "#bef264",
      textPrimary: "#365314",
      textSecondary: "#3f6212",
      border: "#ecfccb",
    },
  },
  {
    name: "rosewater",
    label: "Rosewater",
    type: "light",
    colors: {
      bg: "#fff1f2",
      surface: "#ffffff",
      primary: "#fb7185",
      secondary: "#e11d48",
      accent: "#fda4af",
      textPrimary: "#881337",
      textSecondary: "#9f1239",
      border: "#ffe4e6",
    },
  },
  {
    name: "chai",
    label: "Chai",
    type: "light",
    colors: {
      bg: "#fafaf9",
      surface: "#ffffff",
      primary: "#a8a29e",
      secondary: "#78716c",
      accent: "#d6d3d1",
      textPrimary: "#44403c",
      textSecondary: "#57534e",
      border: "#f5f5f4",
    },
  },
  {
    name: "glacier",
    label: "Glacier",
    type: "light",
    colors: {
      bg: "#f8fafc",
      surface: "#ffffff",
      primary: "#94a3b8",
      secondary: "#64748b",
      accent: "#cbd5e1",
      textPrimary: "#1e293b",
      textSecondary: "#334155",
      border: "#f1f5f9",
    },
  },
  {
    name: "earth",
    label: "Earth",
    type: "light",
    colors: {
      bg: "#fdfcfb",
      surface: "#ffffff",
      primary: "#b91c1c",
      secondary: "#991b1b",
      accent: "#fca5a5",
      textPrimary: "#450a0a",
      textSecondary: "#7f1d1d",
      border: "#fee2e2",
    },
  },
  {
    name: "silk",
    label: "Silk",
    type: "light",
    colors: {
      bg: "#f9fafb",
      surface: "#ffffff",
      primary: "#6b7280",
      secondary: "#4b5563",
      accent: "#d1d5db",
      textPrimary: "#111827",
      textSecondary: "#374151",
      border: "#f3f4f6",
    },
  },
  {
    name: "dew",
    label: "Dew",
    type: "light",
    colors: {
      bg: "#f5fffb",
      surface: "#ffffff",
      primary: "#14b8a6",
      secondary: "#0d9488",
      accent: "#99f6e4",
      textPrimary: "#134e4a",
      textSecondary: "#115e59",
      border: "#ccfbf1",
    },
  },
  {
    name: "papaya",
    label: "Papaya",
    type: "light",
    colors: {
      bg: "#fffaf0",
      surface: "#ffffff",
      primary: "#f97316",
      secondary: "#ea580c",
      accent: "#ffedd5",
      textPrimary: "#7c2d12",
      textSecondary: "#9a3412",
      border: "#ffedd5",
    },
  },
  {
    name: "quartz",
    label: "Quartz",
    type: "light",
    colors: {
      bg: "#fdf2f8",
      surface: "#ffffff",
      primary: "#ec4899",
      secondary: "#db2777",
      accent: "#fbcfe8",
      textPrimary: "#831843",
      textSecondary: "#9d174d",
      border: "#fce7f3",
    },
  },

  // --- DARK SOFT THEMES (16) ---
  {
    name: "dark",
    label: "Slate (Dark)",
    type: "dark",
    colors: {
      bg: "#0f172a",
      surface: "#1e293b",
      primary: "#3b82f6",
      secondary: "#94a3b8",
      accent: "#60a5fa",
      textPrimary: "#f8fafc",
      textSecondary: "#94a3b8",
      border: "#334155",
    },
  },
  {
    name: "midnight",
    label: "Midnight",
    type: "dark",
    colors: {
      bg: "#0a0c1a",
      surface: "#13162a",
      primary: "#6366f1",
      secondary: "#475569",
      accent: "#818cf8",
      textPrimary: "#f1f5f9",
      textSecondary: "#94a3b8",
      border: "#1e293b",
    },
  },
  {
    name: "coal",
    label: "Coal",
    type: "dark",
    colors: {
      bg: "#141414",
      surface: "#1e1e1e",
      primary: "#ffffff",
      secondary: "#71717a",
      accent: "#a1a1aa",
      textPrimary: "#ffffff",
      textSecondary: "#a1a1aa",
      border: "#27272a",
    },
  },
  {
    name: "forest-night",
    label: "Forest Night",
    type: "dark",
    colors: {
      bg: "#022c22",
      surface: "#064e3b",
      primary: "#10b981",
      secondary: "#065f46",
      accent: "#34d399",
      textPrimary: "#ecfdf5",
      textSecondary: "#a7f3d0",
      border: "#065f46",
    },
  },
  {
    name: "deep-sea",
    label: "Deep Sea",
    type: "dark",
    colors: {
      bg: "#083344",
      surface: "#0e7490",
      primary: "#22d3ee",
      secondary: "#0891b2",
      accent: "#67e8f9",
      textPrimary: "#ecfeff",
      textSecondary: "#a5f3fc",
      border: "#155e75",
    },
  },
  {
    name: "plum",
    label: "Plum",
    type: "dark",
    colors: {
      bg: "#2e1065",
      surface: "#4c1d95",
      primary: "#c084fc",
      secondary: "#7c3aed",
      accent: "#d8b4fe",
      textPrimary: "#f5f3ff",
      textSecondary: "#ddd6fe",
      border: "#5b21b6",
    },
  },
  {
    name: "storm",
    label: "Storm",
    type: "dark",
    colors: {
      bg: "#1e293b",
      surface: "#334155",
      primary: "#94a3b8",
      secondary: "#475569",
      accent: "#cbd5e1",
      textPrimary: "#f8fafc",
      textSecondary: "#cbd5e1",
      border: "#475569",
    },
  },
  {
    name: "chocolate",
    label: "Chocolate",
    type: "dark",
    colors: {
      bg: "#1c1917",
      surface: "#292524",
      primary: "#d97706",
      secondary: "#78716c",
      accent: "#fbbf24",
      textPrimary: "#fafaf9",
      textSecondary: "#d6d3d1",
      border: "#44403c",
    },
  },
  {
    name: "bordeaux",
    label: "Bordeaux",
    type: "dark",
    colors: {
      bg: "#450a0a",
      surface: "#7f1d1d",
      primary: "#ef4444",
      secondary: "#991b1b",
      accent: "#f87171",
      textPrimary: "#fef2f2",
      textSecondary: "#fecaca",
      border: "#991b1b",
    },
  },
  {
    name: "evergreen",
    label: "Evergreen",
    type: "dark",
    colors: {
      bg: "#064e3b",
      surface: "#065f46",
      primary: "#10b981",
      secondary: "#047857",
      accent: "#34d399",
      textPrimary: "#ecfdf5",
      textSecondary: "#a7f3d0",
      border: "#047857",
    },
  },
  {
    name: "abyss",
    label: "Abyss",
    type: "dark",
    colors: {
      bg: "#050508",
      surface: "#0d0d12",
      primary: "#3b82f6",
      secondary: "#171717",
      accent: "#60a5fa",
      textPrimary: "#ffffff",
      textSecondary: "#737373",
      border: "#171717",
    },
  },
  {
    name: "titanium",
    label: "Titanium",
    type: "dark",
    colors: {
      bg: "#18181b",
      surface: "#27272a",
      primary: "#e4e4e7",
      secondary: "#52525b",
      accent: "#d4d4d8",
      textPrimary: "#fafafa",
      textSecondary: "#a1a1aa",
      border: "#3f3f46",
    },
  },
  {
    name: "twilight",
    label: "Twilight",
    type: "dark",
    colors: {
      bg: "#1e1b4b",
      surface: "#312e81",
      primary: "#818cf8",
      secondary: "#4338ca",
      accent: "#a5b4fc",
      textPrimary: "#e0e7ff",
      textSecondary: "#c7d2fe",
      border: "#3730a3",
    },
  },
  {
    name: "ink",
    label: "Ink",
    type: "dark",
    colors: {
      bg: "#0f172a",
      surface: "#1e293b",
      primary: "#0ea5e9",
      secondary: "#0369a1",
      accent: "#38bdf8",
      textPrimary: "#f0f9ff",
      textSecondary: "#bae6fd",
      border: "#1e3a8a",
    },
  },
  {
    name: "velvet",
    label: "Velvet",
    type: "dark",
    colors: {
      bg: "#2d0032",
      surface: "#4a004e",
      primary: "#d946ef",
      secondary: "#701a75",
      accent: "#f0abfc",
      textPrimary: "#fdf4ff",
      textSecondary: "#f5d0fe",
      border: "#701a75",
    },
  },
  {
    name: "steel",
    label: "Steel",
    type: "dark",
    colors: {
      bg: "#334155",
      surface: "#475569",
      primary: "#f1f5f9",
      secondary: "#64748b",
      accent: "#e2e8f0",
      textPrimary: "#f8fafc",
      textSecondary: "#cbd5e1",
      border: "#64748b",
    },
  },
];

export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Hindi",
  "Russian",
  "Portuguese",
  "Arabic",
  "Italian",
  "Turkish",
  "Dutch",
];

export const LANGUAGE_TO_FLAG = {
  english: "gb",
  spanish: "es",
  french: "fr",
  german: "de",
  mandarin: "cn",
  japanese: "jp",
  korean: "kr",
  hindi: "in",
  russian: "ru",
  portuguese: "pt",
  arabic: "sa",
  italian: "it",
  turkish: "tr",
  dutch: "nl",
};
